name: siplant_pbm
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.8.0
  firebase_auth: ^4.6.2
  firebase_storage: ^11.2.3
  photo_view: ^0.14.0
  google_maps_flutter: ^2.1.1
  intl: ^0.17.0
  provider: ^6.0.5
  geolocator: ^7.7.0
  http: ^0.13.4
  permission_handler: ^10.3.0
  flutter_icons: ^1.1.0
  loading_animation_widget: ^1.2.0+4
  camera: ^0.10.5+2
  image_picker: ^0.8.9
  geocoding: ^2.1.0
  latlong2: ^0.8.1
  flutter_map: ^0.13.1
  url_launcher: ^6.1.11
  carousel_slider: ^4.0.0

 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
   - assets/


  uses-material-design: true

 